---
# tasks file for hive

# http://mirror.its.dal.ca/apache/hive/hive-2.0.0/apache-hive-2.0.0-bin.tar.gz

- name: stat /tmp/apache-hive-2.0.1-bin.tar.gz
  stat: path=/tmp/apache-hive-2.0.1-bin.tar.gz
  register: hive_binary_stat

- name: Downloading Apache Hive
  get_url: url=http://muug.ca/mirror/apache-dist/hive/hive-2.0.1/apache-hive-2.0.1-bin.tar.gz  dest=/tmp/apache-hive-2.0.1-bin.tar.gz
  when: hive_binary_stat.stat.exists == False

- name: rename file
  command: chown hadoop:hadoop /tmp/apache-hive-2.0.1-bin.tar.gz

#
# - name: copy hive to tmp folder
#   copy: src=apache-hive-2.0.0-bin.tar.gz dest=/tmp/
#   when: hivebinary_stat.stat.exists == False
#   tags:
#     - provision_copy_to_remote

- name: unzip tarball and place in /usr/local/
  command: tar zxf /tmp/apache-hive-2.0.1-bin.tar.gz -C /usr/local/

- name: stat /usr/local/hive
  stat: path=/usr/local/hive
  register: hive_dir_stat

- name: rename file
  command: creates="/usr/local/hive" mv /usr/local/apache-hive-2.0.1-bin/  /usr/local/hive
  when: hive_dir_stat.stat.exists == False

# TODO: This step is going to be manual.
# - name: create mysql metastore
#   command: /usr/local/hive/bin/schematool -dbType mysql -initSchema -userName hiveuser -passWord hivepassword
#   become: yes
#   become_user: hadoop

- name: copy mysql jdbc driver
  command: cp /usr/share/java/mysql-connector-java.jar /usr/local/hive/lib/mysql-connector-java.jar

# TODO: Add 'hive.support.concurrency=true, '
# TODO: Add 'hive.zookeeper.quorum=hadoopmaster,hadoopdata1, hadoopdata2'
- name: setup core-site.xml file
  template: src=hive-site.xml.j2 dest=/usr/local/hive/conf/hive-site.xml
